services:
  - type: web
    name: my-react-app
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
